# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TcYYonW91kRhcuFRtVFRPZRBK4K9UIa3
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
from sqlalchemy import create_engine, text

# Install pymysql if not already installed
# %pip install pymysql

# -------------------------------
# 1. Read the CSV
# -------------------------------

df = pd.read_csv("used_bikes Task 2.csv")

print("Original Data Types")
print(df.dtypes)

print("\nMemory Usage Before Optimization")
print(df.memory_usage(deep=True).sum() / 1024, "KB")


# -------------------------------
# 2. Optimize Data Types
# -------------------------------

# Float64 -> Float32
float_cols = df.select_dtypes(include=["float64"]).columns

for col in float_cols:
    df[col] = df[col].astype("float32")

# Convert Object columns having repeated values to Category

category_cols = ["city", "owner", "brand"]

for col in category_cols:
    df[col] = df[col].astype("category")

# Keep bike_name as string because it is mostly unique
df["bike_name"] = df["bike_name"].astype("string")

print("\nOptimized Data Types")
print(df.dtypes)

print("\nMemory Usage After Optimization")
print(df.memory_usage(deep=True).sum() / 1024, "KB")


# -------------------------------
# 3. Connect MySQL
# -------------------------------

username = "root"
password = "password"
host = "localhost"
database = "bike_db"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}/{database}"
)

table_name = "used_bikes"


# -------------------------------
# 4. Drop Indexes Before Loading
# -------------------------------

with engine.begin() as conn:

    # Drop indexes if already exist

    try:
        conn.execute(text(f"ALTER TABLE {table_name} DROP INDEX idx_city"))
    except:
        pass

    try:
        conn.execute(text(f"ALTER TABLE {table_name} DROP INDEX idx_brand"))
    except:
        pass

    try:
        conn.execute(text(f"ALTER TABLE {table_name} DROP INDEX idx_price"))
    except:
        pass


# -------------------------------
# 5. Insert Data
# -------------------------------

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False,
    chunksize=1000,
    method="multi"
)

print("Data Loaded Successfully")


# -------------------------------
# 6. Create Indexes Again
# -------------------------------

with engine.begin() as conn:

    conn.execute(text(f"CREATE INDEX idx_city ON {table_name}(city)"))
    conn.execute(text(f"CREATE INDEX idx_brand ON {table_name}(brand)"))
    conn.execute(text(f"CREATE INDEX idx_price ON {table_name}(price)"))

print("Indexes Created Successfully")