# -*- coding: utf-8 -*-
"""Task 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajCBLIGTK13MCU_X9P21a0FlRWHbVNu4
"""

import pandas as pd

# Read Excel sheets
data1 = pd.read_excel("Records Matching Task.xlsx", sheet_name="data1")
data2 = pd.read_excel("Records Matching Task.xlsx", sheet_name="data2")

keys = ["Order ID", "Product ID"]

# 1. Present in data1 but missing in data2
missing_in_data2 = (
    data1.merge(data2[keys], on=keys, how="left", indicator=True)
         .query("_merge == 'left_only'")
)

print("Records in data1 but not in data2:", len(missing_in_data2))

# 2. Present in data2 but missing in data1
missing_in_data1 = (
    data2.merge(data1[keys], on=keys, how="left", indicator=True)
         .query("_merge == 'left_only'")
)

print("Records in data2 but not in data1:", len(missing_in_data1))

# 3. Sum of Qty of records missing in data1
qty_sum = missing_in_data1["Qty"].sum()
print("Sum of Qty:", qty_sum)

# 4. Total unique OrderID + ProductID combinations
unique_records = (
    pd.concat([data1[keys], data2[keys]])
      .drop_duplicates()
)

print("Total Unique Records:", len(unique_records))